/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AICopilot: typeof import('./src/components/AICopilot.vue')['default']
    BottomToolbar: typeof import('./src/components/BottomToolbar.vue')['default']
    ClusterSettingsDialog: typeof import('./src/components/ClusterSettingsDialog.vue')['default']
    CollaborationBar: typeof import('./src/components/CollaborationBar.vue')['default']
    ColorLegend: typeof import('./src/components/ColorLegend.vue')['default']
    DashboardPanel: typeof import('./src/components/panels/DashboardPanel.vue')['default']
    DensitySlider: typeof import('./src/components/DensitySlider.vue')['default']
    DifyChat: typeof import('./src/components/DifyChat.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Graph2D: typeof import('./src/components/Graph2D.vue')['default']
    GraphDebugPanel: typeof import('./src/components/GraphDebugPanel.vue')['default']
    ImportDashboard: typeof import('./src/components/ImportDashboard.vue')['default']
    KnowledgeForm: typeof import('./src/components/KnowledgeForm.vue')['default']
    NexusBreadcrumb: typeof import('./src/components/NexusBreadcrumb.vue')['default']
    NexusPanel: typeof import('./src/components/NexusPanel.vue')['default']
    NodeInspectorPanel: typeof import('./src/components/NodeInspectorPanel.vue')['default']
    RAGFlowDocManager: typeof import('./src/components/RAGFlowDocManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StatsBar: typeof import('./src/components/StatsBar.vue')['default']
    ZoomControls: typeof import('./src/components/ZoomControls.vue')['default']
  }
}
